FROM python:3.9-alpine

WORKDIR /app

COPY requirements.txt .

RUN pip install pip==21.3.1
RUN pip install -r requirements.txt

COPY app.py .
COPY movies.db .
COPY templates ./templates
RUN  chmod 777 /app
# COPY assets ./assets


CMD ["python3", "app.py"]